require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const path = require('path');
const errorHandler = require('./middleware/errorHandler');
const routes = require('./routes/index');
const app = express();
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: '*' }));
app.use(express.json({ limit: '10kb' }));
app.use(express.static(path.join(__dirname, '../public')));
app.get('/health', (req, res) => res.status(200).json({ status: 'ShopCore API is running' }));
app.use('/api', routes);
app.get('/', (req, res) => res.sendFile(path.join(__dirname, '../public/index.html')));
app.use((req, res) => res.status(404).json({ success: false, message: `Route ${req.originalUrl} not found` }));
app.use(errorHandler);
module.exports = app;
